import type { Match, Player, Sponsor, Team, Venue } from "./types";

export const venues: Venue[] = [
  {
    id: "ven_01",
    name: "Gimnasio Municipal de Melipilla",
    address: "Ortúzar 1371",
    city: "9581442 Melipilla, Región Metropolitana",
    coordinates: { lat: -33.696717, lng: -71.215636 },
  },
  {
    id: "ven_02",
    name: "Gimnasio Municipal de San Antonio",
    address: "Av. Barros Luco 1881, San Antonio",
    city: "San Antonio",
    coordinates: { lat: -33.5928, lng: -71.6067 },
  },
  {
    id: "ven_03",
    name: "Gimnasio Municipal de Curacaví",
    address: "Ambrosio O'Higgins 1550, Curacaví",
    city: "Curacaví",
    coordinates: { lat: -33.4056, lng: -71.1436 },
  },
];

export const teams: Team[] = [
  {
    id: "tm_01",
    name: "Club Vóley Santiago",
    short_name: "STGO",
    city: "Santiago",
    logo_color: "#DC2626",
    coach: "Prof. Roberto Morales",
  },
  {
    id: "tm_02",
    name: "Deportivo San Antonio",
    short_name: "SANA",
    city: "San Antonio",
    logo_color: "#2563EB",
    coach: "Prof. Camila Reyes",
  },
  {
    id: "tm_03",
    name: "Halcones de Valparaíso",
    short_name: "VALP",
    city: "Valparaíso",
    logo_color: "#F59E0B",
    coach: "Prof. Andrés Vera",
  },
  {
    id: "tm_04",
    name: "Rancagua Vóley Club",
    short_name: "RANC",
    city: "Rancagua",
    logo_color: "#059669",
    coach: "Prof. Isabel Núñez",
  },
  {
    id: "tm_05",
    name: "Talca Spikers",
    short_name: "TALC",
    city: "Talca",
    logo_color: "#7C3AED",
    coach: "Prof. Diego Fuentes",
  },
  {
    id: "tm_06",
    name: "Cóndores de Ñuñoa",
    short_name: "NUNO",
    city: "Santiago",
    logo_color: "#0891B2",
    coach: "Prof. Paulina Salas",
  },
];

const mkPlayers = (team_id: string, coachInitials: string): Player[] => [
  { id: `${team_id}_p1`, team_id, number: 1, name: `Armador 1 (${coachInitials})`, position: "Armador", is_captain: true },
  { id: `${team_id}_p2`, team_id, number: 2, name: `Armador 2 (${coachInitials})`, position: "Armador", is_captain: false },
  { id: `${team_id}_p3`, team_id, number: 3, name: `Punta 1 (${coachInitials})`, position: "Punta/Receptor", is_captain: false },
  { id: `${team_id}_p4`, team_id, number: 4, name: `Punta 2 (${coachInitials})`, position: "Punta/Receptor", is_captain: false },
  { id: `${team_id}_p5`, team_id, number: 5, name: `Punta 3 (${coachInitials})`, position: "Punta/Receptor", is_captain: false },
  { id: `${team_id}_p6`, team_id, number: 6, name: `Punta 4 (${coachInitials})`, position: "Punta/Receptor", is_captain: false },
  { id: `${team_id}_p7`, team_id, number: 7, name: `Central 1 (${coachInitials})`, position: "Central", is_captain: false },
  { id: `${team_id}_p8`, team_id, number: 8, name: `Central 2 (${coachInitials})`, position: "Central", is_captain: false },
  { id: `${team_id}_p9`, team_id, number: 9, name: `Central 3 (${coachInitials})`, position: "Central", is_captain: false },
  { id: `${team_id}_p10`, team_id, number: 10, name: `Opuesto 1 (${coachInitials})`, position: "Opuesto", is_captain: false },
  { id: `${team_id}_p11`, team_id, number: 11, name: `Opuesto 2 (${coachInitials})`, position: "Opuesto", is_captain: false },
  { id: `${team_id}_p12`, team_id, number: 12, name: `Líbero 1 (${coachInitials})`, position: "Líbero", is_captain: false },
  { id: `${team_id}_p13`, team_id, number: 13, name: `Líbero 2 (${coachInitials})`, position: "Líbero", is_captain: false },
  { id: `${team_id}_p14`, team_id, number: 14, name: `Universal (${coachInitials})`, position: "Punta/Receptor", is_captain: false },
];

export const players: Player[] = [
  // --- JUGADORES DE CLUB VÓLEY SANTIAGO (tm_01) ---
  { id: "tm_01_p1", team_id: "tm_01", number: 1, name: "Ignacio Soto", position: "Armador", is_captain: true },
  { id: "tm_01_p2", team_id: "tm_01", number: 5, name: "Lucas Mella", position: "Armador", is_captain: false },
  { id: "tm_01_p3", team_id: "tm_01", number: 7, name: "Gabriel Gómez", position: "Punta/Receptor", is_captain: false },
  { id: "tm_01_p4", team_id: "tm_01", number: 9, name: "Matías Rojas", position: "Punta/Receptor", is_captain: false },
  { id: "tm_01_p5", team_id: "tm_01", number: 11, name: "Diego Fernández", position: "Punta/Receptor", is_captain: false },
  { id: "tm_01_p6", team_id: "tm_01", number: 13, name: "Sebastián Torres", position: "Punta/Receptor", is_captain: false },
  { id: "tm_01_p7", team_id: "tm_01", number: 15, name: "Cristóbal Riquelme", position: "Central", is_captain: false },
  { id: "tm_01_p8", team_id: "tm_01", number: 17, name: "Nicolás Araya", position: "Central", is_captain: false },
  { id: "tm_01_p9", team_id: "tm_01", number: 19, name: "Tomás Valenzuela", position: "Central", is_captain: false },
  { id: "tm_01_p10", team_id: "tm_01", number: 21, name: "Felipe Rojas", position: "Opuesto", is_captain: false },
  { id: "tm_01_p11", team_id: "tm_01", number: 23, name: "Joaquín Pérez", position: "Opuesto", is_captain: false },
  { id: "tm_01_p12", team_id: "tm_01", number: 25, name: "Martín Salazar", position: "Líbero", is_captain: false },
  { id: "tm_01_p13", team_id: "tm_01", number: 27, name: "Ignacio Aravena", position: "Líbero", is_captain: false },
  { id: "tm_01_p14", team_id: "tm_01", number: 29, name: "Maximiliano Rojas", position: "Punta/Receptor", is_captain: false },

  // --- JUGADORES DE DEPORTIVO SAN ANTONIO (tm_02) ---
  { id: "tm_02_p1", team_id: "tm_02", number: 2, name: "Vicente Rojas", position: "Armador", is_captain: true },
  { id: "tm_02_p2", team_id: "tm_02", number: 8, name: "Tomás Álvarez", position: "Armador", is_captain: false },
  { id: "tm_02_p3", team_id: "tm_02", number: 10, name: "Diego Soto", position: "Punta/Receptor", is_captain: false },
  { id: "tm_02_p4", team_id: "tm_02", number: 12, name: "Joaquín Rojas", position: "Punta/Receptor", is_captain: false },
  { id: "tm_02_p5", team_id: "tm_02", number: 14, name: "Nicolás Torres", position: "Punta/Receptor", is_captain: false },
  { id: "tm_02_p6", team_id: "tm_02", number: 16, name: "Felipe Araya", position: "Central", is_captain: false },
  { id: "tm_02_p7", team_id: "tm_02", number: 18, name: "Cristóbal Pérez", position: "Central", is_captain: false },
  { id: "tm_02_p8", team_id: "tm_02", number: 20, name: "Maximiliano Rojas", position: "Central", is_captain: false },
  { id: "tm_02_p9", team_id: "tm_02", number: 22, name: "Martín Salazar", position: "Opuesto", is_captain: false },
  { id: "tm_02_p10", team_id: "tm_02", number: 24, name: "Ignacio Aravena", position: "Opuesto", is_captain: false },
  { id: "tm_02_p11", team_id: "tm_02", number: 26, name: "Sebastián Torres", position: "Líbero", is_captain: false },
  { id: "tm_02_p12", team_id: "tm_02", number: 28, name: "Gabriel Gómez", position: "Líbero", is_captain: false },
  { id: "tm_02_p13", team_id: "tm_02", number: 30, name: "Matías Rojas", position: "Punta/Receptor", is_captain: false },
  { id: "tm_02_p14", team_id: "tm_02", number: 32, name: "Lucas Mella", position: "Armador", is_captain: false },
  // --- JUGADORES DE HALCONES DE VALPARAÍSO (tm_03) ---
  { id: "tm_03_p1", team_id: "tm_03", number: 3, name: "Armador 1 (AV)", position: "Armador", is_captain: true },
  { id: "tm_03_p2", team_id: "tm_03", number: 4, name: "Armador 2 (AV)", position: "Armador", is_captain: false },
  { id: "tm_03_p3", team_id: "tm_03", number: 5, name: "Punta 1 (AV)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_03_p4", team_id: "tm_03", number: 6, name: "Punta 2 (AV)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_03_p5", team_id: "tm_03", number: 7, name: "Punta 3 (AV)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_03_p6", team_id: "tm_03", number: 8, name: "Punta 4 (AV)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_03_p7", team_id: "tm_03", number: 9, name: "Central 1 (AV)", position: "Central", is_captain: false },
  { id: "tm_03_p8", team_id: "tm_03", number: 10, name: "Central 2 (AV)", position: "Central", is_captain: false },
  { id: "tm_03_p9", team_id: "tm_03", number: 11, name: "Central 3 (AV)", position: "Central", is_captain: false },
  { id: "tm_03_p10", team_id: "tm_03", number: 12, name: "Opuesto 1 (AV)", position: "Opuesto", is_captain: false },
  { id: "tm_03_p11", team_id: "tm_03", number: 13, name: "Opuesto 2 (AV)", position: "Opuesto", is_captain: false },
  { id: "tm_03_p12", team_id: "tm_03", number: 14, name: "Líbero 1 (AV)", position: "Líbero", is_captain: false },
  { id: "tm_03_p13", team_id: "tm_03", number: 15, name: "Líbero 2 (AV)", position: "Líbero", is_captain: false },
  { id: "tm_03_p14", team_id: "tm_03", number: 16, name: "Universal (AV)", position: "Punta/Receptor", is_captain: false },
  // --- JUGADORES DE RANCAGUA VÓLEY CLUB (tm_04) ---
  { id: "tm_04_p1", team_id: "tm_04", number: 1, name: "Armador 1 (RV)", position: "Armador", is_captain: true },
  { id: "tm_04_p2", team_id: "tm_04", number: 2, name: "Armador 2 (RV)", position: "Armador", is_captain: false },
  { id: "tm_04_p3", team_id: "tm_04", number: 3, name: "Punta 1 (RV)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_04_p4", team_id: "tm_04", number: 4, name: "Punta 2 (RV)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_04_p5", team_id: "tm_04", number: 5, name: "Punta 3 (RV)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_04_p6", team_id: "tm_04", number: 6, name: "Punta 4 (RV)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_04_p7", team_id: "tm_04", number: 7, name: "Central 1 (RV)", position: "Central", is_captain: false },
  { id: "tm_04_p8", team_id: "tm_04", number: 8, name: "Central 2 (RV)", position: "Central", is_captain: false },
  { id: "tm_04_p9", team_id: "tm_04", number: 9, name: "Central 3 (RV)", position: "Central", is_captain: false },
  { id: "tm_04_p10", team_id: "tm_04", number: 10, name: "Opuesto 1 (RV)", position: "Opuesto", is_captain: false },
  { id: "tm_04_p11", team_id: "tm_04", number: 11, name: "Opuesto 2 (RV)", position: "Opuesto", is_captain: false },
  { id: "tm_04_p12", team_id: "tm_04", number: 12, name: "Líbero 1 (RV)", position: "Líbero", is_captain: false },
  { id: "tm_04_p13", team_id: "tm_04", number: 13, name: "Líbero 2 (RV)", position: "Líbero", is_captain: false },
  { id: "tm_04_p14", team_id: "tm_04", number: 14, name: "Universal (RV)", position: "Punta/Receptor", is_captain: false },
  // --- JUGADORES DE TALCA SPIKERS (tm_05) ---
  { id: "tm_05_p1", team_id: "tm_05", number: 1, name: "Armador 1 (TS)", position: "Armador", is_captain: true },
  { id: "tm_05_p2", team_id: "tm_05", number: 2, name: "Armador 2 (TS)", position: "Armador", is_captain: false },
  { id: "tm_05_p3", team_id: "tm_05", number: 3, name: "Punta 1 (TS)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_05_p4", team_id: "tm_05", number: 4, name: "Punta 2 (TS)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_05_p5", team_id: "tm_05", number: 5, name: "Punta 3 (TS)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_05_p6", team_id: "tm_05", number: 6, name: "Punta 4 (TS)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_05_p7", team_id: "tm_05", number: 7, name: "Central 1 (TS)", position: "Central", is_captain: false },
  { id: "tm_05_p8", team_id: "tm_05", number: 8, name: "Central 2 (TS)", position: "Central", is_captain: false },
  { id: "tm_05_p9", team_id: "tm_05", number: 9, name: "Central 3 (TS)", position: "Central", is_captain: false },
  { id: "tm_05_p10", team_id: "tm_05", number: 10, name: "Opuesto 1 (TS)", position: "Opuesto", is_captain: false },
  { id: "tm_05_p11", team_id: "tm_05", number: 11, name: "Opuesto 2 (TS)", position: "Opuesto", is_captain: false },
  { id: "tm_05_p12", team_id: "tm_05", number: 12, name: "Líbero 1 (TS)", position: "Líbero", is_captain: false },
  { id: "tm_05_p13", team_id: "tm_05", number: 13, name: "Líbero 2 (TS)", position: "Líbero", is_captain: false },
  { id: "tm_05_p14", team_id: "tm_05", number: 14, name: "Universal (TS)", position: "Punta/Receptor", is_captain: false },
  // --- JUGADORES DE CÓNDORES DE ÑUÑOA (tm_06) ---
  { id: "tm_06_p1", team_id: "tm_06", number: 1, name: "Armador 1 (CN)", position: "Armador", is_captain: true },
  { id: "tm_06_p2", team_id: "tm_06", number: 2, name: "Armador 2 (CN)", position: "Armador", is_captain: false },
  { id: "tm_06_p3", team_id: "tm_06", number: 3, name: "Punta 1 (CN)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_06_p4", team_id: "tm_06", number: 4, name: "Punta 2 (CN)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_06_p5", team_id: "tm_06", number: 5, name: "Punta 3 (CN)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_06_p6", team_id: "tm_06", number: 6, name: "Punta 4 (CN)", position: "Punta/Receptor", is_captain: false },
  { id: "tm_06_p7", team_id: "tm_06", number: 7, name: "Central 1 (CN)", position: "Central", is_captain: false },
  { id: "tm_06_p8", team_id: "tm_06", number: 8, name: "Central 2 (CN)", position: "Central", is_captain: false },
  { id: "tm_06_p9", team_id: "tm_06", number: 9, name: "Central 3 (CN)", position: "Central", is_captain: false },
  { id: "tm_06_p10", team_id: "tm_06", number: 10, name: "Opuesto 1 (CN)", position: "Opuesto", is_captain: false },
  { id: "tm_06_p11", team_id: "tm_06", number: 11, name: "Opuesto 2 (CN)", position: "Opuesto", is_captain: false },
  { id: "tm_06_p12", team_id: "tm_06", number: 12, name: "Líbero 1 (CN)", position: "Líbero", is_captain: false },
  { id: "tm_06_p13", team_id: "tm_06", number: 13, name: "Líbero 2 (CN)", position: "Líbero", is_captain: false },
];

export const matches: Match[] = [
  {
    id: "mt_101",
    matchday: 1,
    phase: "regular",
    datetime: "2026-08-15T15:30:00",
    status: "finished",
    home_team_id: "tm_01",
    away_team_id: "tm_02",
    venue_id: "ven_02",
    score: {
      home_sets: 3,
      away_sets: 1,
      set_details: [
        { set: 1, home: 25, away: 20 },
        { set: 2, home: 22, away: 25 },
        { set: 3, home: 25, away: 18 },
        { set: 4, home: 25, away: 21 },
      ],
    },
  },
  {
    id: "mt_102",
    matchday: 1,
    phase: "regular",
    datetime: "2026-08-15T17:30:00",
    status: "finished",
    home_team_id: "tm_03",
    away_team_id: "tm_04",
    venue_id: "ven_03",
    score: {
      home_sets: 3,
      away_sets: 2,
      set_details: [
        { set: 1, home: 25, away: 22 },
        { set: 2, home: 23, away: 25 },
        { set: 3, home: 25, away: 19 },
        { set: 4, home: 20, away: 25 },
        { set: 5, home: 15, away: 12 },
      ],
    },
  },
  {
    id: "mt_103",
    matchday: 1,
    phase: "regular",
    datetime: "2026-08-16T11:00:00",
    status: "finished",
    home_team_id: "tm_05",
    away_team_id: "tm_06",
    venue_id: "ven_03",
    score: {
      home_sets: 0,
      away_sets: 3,
      set_details: [
        { set: 1, home: 21, away: 25 },
        { set: 2, home: 19, away: 25 },
        { set: 3, home: 23, away: 25 },
      ],
    },
  },
  {
    id: "mt_201",
    matchday: 2,
    phase: "regular",
    datetime: "2026-08-22T15:30:00",
    status: "finished",
    home_team_id: "tm_02",
    away_team_id: "tm_03",
    venue_id: "ven_01",
    score: {
      home_sets: 3,
      away_sets: 0,
      set_details: [
        { set: 1, home: 25, away: 18 },
        { set: 2, home: 25, away: 22 },
        { set: 3, home: 25, away: 20 },
      ],
    },
  },
  {
    id: "mt_202",
    matchday: 2,
    phase: "regular",
    datetime: "2026-08-22T17:30:00",
    status: "finished",
    home_team_id: "tm_04",
    away_team_id: "tm_05",
    venue_id: "ven_01",
    score: {
      home_sets: 3,
      away_sets: 1,
      set_details: [
        { set: 1, home: 25, away: 23 },
        { set: 2, home: 25, away: 21 },
        { set: 3, home: 22, away: 25 },
        { set: 4, home: 25, away: 19 },
      ],
    },
  },
  {
    id: "mt_203",
    matchday: 2,
    phase: "regular",
    datetime: "2026-08-23T11:00:00",
    status: "live",
    home_team_id: "tm_06",
    away_team_id: "tm_01",
    venue_id: "ven_02",
    score: {
      home_sets: 1,
      away_sets: 1,
      set_details: [
        { set: 1, home: 25, away: 22 },
        { set: 2, home: 20, away: 25 },
      ],
    },
  },
  {
    id: "mt_301",
    matchday: 3,
    phase: "regular",
    datetime: "2026-08-29T15:30:00",
    status: "scheduled",
    home_team_id: "tm_01",
    away_team_id: "tm_03",
    venue_id: "ven_02",
    score: { home_sets: 0, away_sets: 0, set_details: [] },
  },
  {
    id: "mt_302",
    matchday: 3,
    phase: "regular",
    datetime: "2026-08-29T17:30:00",
    status: "scheduled",
    home_team_id: "tm_02",
    away_team_id: "tm_05",
    venue_id: "ven_01",
    score: { home_sets: 0, away_sets: 0, set_details: [] },
  },
  {
    id: "mt_303",
    matchday: 3,
    phase: "regular",
    datetime: "2026-08-30T11:00:00",
    status: "scheduled",
    home_team_id: "tm_04",
    away_team_id: "tm_06",
    venue_id: "ven_01",
    score: { home_sets: 0, away_sets: 0, set_details: [] },
  },
  {
    id: "mt_401",
    matchday: 4,
    phase: "regular",
    datetime: "2026-09-05T15:30:00",
    status: "scheduled",
    home_team_id: "tm_03",
    away_team_id: "tm_05",
    venue_id: "ven_03",
    score: { home_sets: 0, away_sets: 0, set_details: [] },
  },
  {
    id: "mt_402",
    matchday: 4,
    phase: "regular",
    datetime: "2026-09-05T17:30:00",
    status: "scheduled",
    home_team_id: "tm_06",
    away_team_id: "tm_02",
    venue_id: "ven_02",
    score: { home_sets: 0, away_sets: 0, set_details: [] },
  },
  {
    id: "mt_403",
    matchday: 4,
    phase: "regular",
    datetime: "2026-09-06T11:00:00",
    status: "scheduled",
    home_team_id: "tm_01",
    away_team_id: "tm_04",
    venue_id: "ven_02",
    score: { home_sets: 0, away_sets: 0, set_details: [] },
  },
  // Playoffs (empty scheduled)
  {
    id: "mt_sf1",
    matchday: 1,
    phase: "playoffs",
    datetime: "2026-10-10T16:00:00",
    status: "scheduled",
    home_team_id: "tm_02",
    away_team_id: "tm_04",
    venue_id: "ven_02",
    score: { home_sets: 0, away_sets: 0, set_details: [] },
  },
  {
    id: "mt_sf2",
    matchday: 1,
    phase: "playoffs",
    datetime: "2026-10-10T18:00:00",
    status: "scheduled",
    home_team_id: "tm_06",
    away_team_id: "tm_01",
    venue_id: "ven_02",
    score: { home_sets: 0, away_sets: 0, set_details: [] },
  },
];

// Auspiciadores del torneo. Vacío por defecto: mientras no haya logos, el home
// muestra una invitación a auspiciar en su lugar. Para sumar uno real, agrega
// un objeto como el de ejemplo (comentado) con el logo del sponsor.
export const sponsors: Sponsor[] = [
  // {
  //   id: "sp_01",
  //   name: "Nombre del auspiciador",
  //   logo_url: "/sponsors/nombre-logo.png",
  //   website_url: "https://ejemplo.cl",
  //   tier: "oro",
  // },
];
