/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as PosicionesRouteImport } from './routes/posiciones'
import { Route as ReglamentoRouteImport } from './routes/reglamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const PosicionesRoute = PosicionesRouteImport.update({
  id: '/posiciones',
  path: '/posiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglamentoRoute = ReglamentoRouteImport.update({
  id: '/reglamento',
  path: '/reglamento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendario': typeof CalendarioRoute
  '/equipos': typeof EquiposRoute
  '/posiciones': typeof PosicionesRoute
  '/reglamento': typeof ReglamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendario': typeof CalendarioRoute
  '/equipos': typeof EquiposRoute
  '/posiciones': typeof PosicionesRoute
  '/reglamento': typeof ReglamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendario': typeof CalendarioRoute
  '/equipos': typeof EquiposRoute
  '/posiciones': typeof PosicionesRoute
  '/reglamento': typeof ReglamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/calendario' | '/equipos' | '/posiciones' | '/reglamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/admin' | '/calendario' | '/equipos' | '/posiciones' | '/reglamento'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendario'
    | '/equipos'
    | '/posiciones'
    | '/reglamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarioRoute: typeof CalendarioRoute
  EquiposRoute: typeof EquiposRoute
  PosicionesRoute: typeof PosicionesRoute
  ReglamentoRoute: typeof ReglamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posiciones': {
      id: '/posiciones'
      path: '/posiciones'
      fullPath: '/posiciones'
      preLoaderRoute: typeof PosicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglamento': {
      id: '/reglamento'
      path: '/reglamento'
      fullPath: '/reglamento'
      preLoaderRoute: typeof ReglamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarioRoute: CalendarioRoute,
  EquiposRoute: EquiposRoute,
  PosicionesRoute: PosicionesRoute,
  ReglamentoRoute: ReglamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
